//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAhorcado.ServiciosAhorcado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaLogin", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class RespuestaLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoAhorcado.ServiciosAhorcado.Usuario InformacionUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsuarioCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoAhorcado.ServiciosAhorcado.Usuario InformacionUsuario {
            get {
                return this.InformacionUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionUsuarioField, value) != true)) {
                    this.InformacionUsuarioField = value;
                    this.RaisePropertyChanged("InformacionUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioCorrecto {
            get {
                return this.UsuarioCorrectoField;
            }
            set {
                if ((this.UsuarioCorrectoField.Equals(value) != true)) {
                    this.UsuarioCorrectoField = value;
                    this.RaisePropertyChanged("UsuarioCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMaternoField, value) != true)) {
                    this.apellidoMaternoField = value;
                    this.RaisePropertyChanged("apellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPaternoField, value) != true)) {
                    this.apellidoPaternoField = value;
                    this.RaisePropertyChanged("apellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int filasAfectadasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int filasAfectadas {
            get {
                return this.filasAfectadasField;
            }
            set {
                if ((this.filasAfectadasField.Equals(value) != true)) {
                    this.filasAfectadasField = value;
                    this.RaisePropertyChanged("filasAfectadas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Palabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((this.categoriaField.Equals(value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPalabra {
            get {
                return this.idPalabraField;
            }
            set {
                if ((this.idPalabraField.Equals(value) != true)) {
                    this.idPalabraField = value;
                    this.RaisePropertyChanged("idPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCategoria {
            get {
                return this.nombreCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreCategoriaField, value) != true)) {
                    this.nombreCategoriaField = value;
                    this.RaisePropertyChanged("nombreCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioRetadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioRetadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int oportunidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int palabraIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                if ((this.categoriaIdField.Equals(value) != true)) {
                    this.categoriaIdField = value;
                    this.RaisePropertyChanged("categoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuarioRetador {
            get {
                return this.idUsuarioRetadorField;
            }
            set {
                if ((this.idUsuarioRetadorField.Equals(value) != true)) {
                    this.idUsuarioRetadorField = value;
                    this.RaisePropertyChanged("idUsuarioRetador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuarioRetador {
            get {
                return this.nombreUsuarioRetadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioRetadorField, value) != true)) {
                    this.nombreUsuarioRetadorField = value;
                    this.RaisePropertyChanged("nombreUsuarioRetador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oportunidades {
            get {
                return this.oportunidadesField;
            }
            set {
                if ((this.oportunidadesField.Equals(value) != true)) {
                    this.oportunidadesField = value;
                    this.RaisePropertyChanged("oportunidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int palabraId {
            get {
                return this.palabraIdField;
            }
            set {
                if ((this.palabraIdField.Equals(value) != true)) {
                    this.palabraIdField = value;
                    this.RaisePropertyChanged("palabraId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntajeGlobal", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class PuntajeGlobal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioRetadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioRetradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPuntaje {
            get {
                return this.idPuntajeField;
            }
            set {
                if ((this.idPuntajeField.Equals(value) != true)) {
                    this.idPuntajeField = value;
                    this.RaisePropertyChanged("idPuntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuarioRetador {
            get {
                return this.idUsuarioRetadorField;
            }
            set {
                if ((this.idUsuarioRetadorField.Equals(value) != true)) {
                    this.idUsuarioRetadorField = value;
                    this.RaisePropertyChanged("idUsuarioRetador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuarioRetrador {
            get {
                return this.nombreUsuarioRetradorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioRetradorField, value) != true)) {
                    this.nombreUsuarioRetradorField = value;
                    this.RaisePropertyChanged("nombreUsuarioRetrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntos {
            get {
                return this.puntosField;
            }
            set {
                if ((this.puntosField.Equals(value) != true)) {
                    this.puntosField = value;
                    this.RaisePropertyChanged("puntos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosAhorcado.IAhorcadoSVC")]
    public interface IAhorcadoSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/LogIn", ReplyAction="http://tempuri.org/IAhorcadoSVC/LogInResponse")]
        ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/LogIn", ReplyAction="http://tempuri.org/IAhorcadoSVC/LogInResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin> LogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/RegistrarUsuario", ReplyAction="http://tempuri.org/IAhorcadoSVC/RegistrarUsuarioResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Mensaje RegistrarUsuario(ProyectoAhorcado.ServiciosAhorcado.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/RegistrarUsuario", ReplyAction="http://tempuri.org/IAhorcadoSVC/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> RegistrarUsuarioAsync(ProyectoAhorcado.ServiciosAhorcado.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/checarLetra", ReplyAction="http://tempuri.org/IAhorcadoSVC/checarLetraResponse")]
        System.Collections.Generic.List<int> checarLetra(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/checarLetra", ReplyAction="http://tempuri.org/IAhorcadoSVC/checarLetraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> checarLetraAsync(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/iniciarJuego", ReplyAction="http://tempuri.org/IAhorcadoSVC/iniciarJuegoResponse")]
        void iniciarJuego(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/iniciarJuego", ReplyAction="http://tempuri.org/IAhorcadoSVC/iniciarJuegoResponse")]
        System.Threading.Tasks.Task iniciarJuegoAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/getLetraEscogida", ReplyAction="http://tempuri.org/IAhorcadoSVC/getLetraEscogidaResponse")]
        char getLetraEscogida();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/getLetraEscogida", ReplyAction="http://tempuri.org/IAhorcadoSVC/getLetraEscogidaResponse")]
        System.Threading.Tasks.Task<char> getLetraEscogidaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/setLetraEscogida", ReplyAction="http://tempuri.org/IAhorcadoSVC/setLetraEscogidaResponse")]
        void setLetraEscogida(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/setLetraEscogida", ReplyAction="http://tempuri.org/IAhorcadoSVC/setLetraEscogidaResponse")]
        System.Threading.Tasks.Task setLetraEscogidaAsync(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPalabras", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPalabrasResponse")]
        System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Palabra> obtenerPalabras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPalabras", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPalabrasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Palabra>> obtenerPalabrasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerCategorias", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerCategoriasResponse")]
        System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Categoria> obtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerCategorias", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerCategoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Categoria>> obtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPartidasDisponiblesResponse")]
        System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Partida> obtenerPartidasDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Partida>> obtenerPartidasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/crearNuevaPartida", ReplyAction="http://tempuri.org/IAhorcadoSVC/crearNuevaPartidaResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Mensaje crearNuevaPartida(ProyectoAhorcado.ServiciosAhorcado.Partida partidaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/crearNuevaPartida", ReplyAction="http://tempuri.org/IAhorcadoSVC/crearNuevaPartidaResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> crearNuevaPartidaAsync(ProyectoAhorcado.ServiciosAhorcado.Partida partidaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/actualizarEstadoPartida", ReplyAction="http://tempuri.org/IAhorcadoSVC/actualizarEstadoPartidaResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Mensaje actualizarEstadoPartida(int idPartida, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/actualizarEstadoPartida", ReplyAction="http://tempuri.org/IAhorcadoSVC/actualizarEstadoPartidaResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> actualizarEstadoPartidaAsync(int idPartida, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerUsuariosRegistrados", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerUsuariosRegistradosResponse")]
        System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Usuario> obtenerUsuariosRegistrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerUsuariosRegistrados", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerUsuariosRegistradosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Usuario>> obtenerUsuariosRegistradosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPartidaPorID", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPartidaPorIDResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Partida obtenerPartidaPorID(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPartidaPorID", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPartidaPorIDResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Partida> obtenerPartidaPorIDAsync(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPalabraPorID", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPalabraPorIDResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Palabra obtenerPalabraPorID(int idPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPalabraPorID", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPalabraPorIDResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Palabra> obtenerPalabraPorIDAsync(int idPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/actualizarIDRetador", ReplyAction="http://tempuri.org/IAhorcadoSVC/actualizarIDRetadorResponse")]
        ProyectoAhorcado.ServiciosAhorcado.Mensaje actualizarIDRetador(int idRetador, int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/actualizarIDRetador", ReplyAction="http://tempuri.org/IAhorcadoSVC/actualizarIDRetadorResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> actualizarIDRetadorAsync(int idRetador, int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPuntajeGlobal", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPuntajeGlobalResponse")]
        System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.PuntajeGlobal> obtenerPuntajeGlobal(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/obtenerPuntajeGlobal", ReplyAction="http://tempuri.org/IAhorcadoSVC/obtenerPuntajeGlobalResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.PuntajeGlobal>> obtenerPuntajeGlobalAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAhorcadoSVCChannel : ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AhorcadoSVCClient : System.ServiceModel.ClientBase<ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC>, ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC {
        
        public AhorcadoSVCClient() {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AhorcadoSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Mensaje RegistrarUsuario(ProyectoAhorcado.ServiciosAhorcado.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> RegistrarUsuarioAsync(ProyectoAhorcado.ServiciosAhorcado.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        
        public System.Collections.Generic.List<int> checarLetra(char letra) {
            return base.Channel.checarLetra(letra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> checarLetraAsync(char letra) {
            return base.Channel.checarLetraAsync(letra);
        }
        
        public void iniciarJuego(string palabra) {
            base.Channel.iniciarJuego(palabra);
        }
        
        public System.Threading.Tasks.Task iniciarJuegoAsync(string palabra) {
            return base.Channel.iniciarJuegoAsync(palabra);
        }
        
        public char getLetraEscogida() {
            return base.Channel.getLetraEscogida();
        }
        
        public System.Threading.Tasks.Task<char> getLetraEscogidaAsync() {
            return base.Channel.getLetraEscogidaAsync();
        }
        
        public void setLetraEscogida(char letra) {
            base.Channel.setLetraEscogida(letra);
        }
        
        public System.Threading.Tasks.Task setLetraEscogidaAsync(char letra) {
            return base.Channel.setLetraEscogidaAsync(letra);
        }
        
        public System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Palabra> obtenerPalabras() {
            return base.Channel.obtenerPalabras();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Palabra>> obtenerPalabrasAsync() {
            return base.Channel.obtenerPalabrasAsync();
        }
        
        public System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Categoria> obtenerCategorias() {
            return base.Channel.obtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Categoria>> obtenerCategoriasAsync() {
            return base.Channel.obtenerCategoriasAsync();
        }
        
        public System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Partida> obtenerPartidasDisponibles() {
            return base.Channel.obtenerPartidasDisponibles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Partida>> obtenerPartidasDisponiblesAsync() {
            return base.Channel.obtenerPartidasDisponiblesAsync();
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Mensaje crearNuevaPartida(ProyectoAhorcado.ServiciosAhorcado.Partida partidaNueva) {
            return base.Channel.crearNuevaPartida(partidaNueva);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> crearNuevaPartidaAsync(ProyectoAhorcado.ServiciosAhorcado.Partida partidaNueva) {
            return base.Channel.crearNuevaPartidaAsync(partidaNueva);
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Mensaje actualizarEstadoPartida(int idPartida, string estado) {
            return base.Channel.actualizarEstadoPartida(idPartida, estado);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> actualizarEstadoPartidaAsync(int idPartida, string estado) {
            return base.Channel.actualizarEstadoPartidaAsync(idPartida, estado);
        }
        
        public System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Usuario> obtenerUsuariosRegistrados() {
            return base.Channel.obtenerUsuariosRegistrados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.Usuario>> obtenerUsuariosRegistradosAsync() {
            return base.Channel.obtenerUsuariosRegistradosAsync();
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Partida obtenerPartidaPorID(int idPartida) {
            return base.Channel.obtenerPartidaPorID(idPartida);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Partida> obtenerPartidaPorIDAsync(int idPartida) {
            return base.Channel.obtenerPartidaPorIDAsync(idPartida);
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Palabra obtenerPalabraPorID(int idPalabra) {
            return base.Channel.obtenerPalabraPorID(idPalabra);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Palabra> obtenerPalabraPorIDAsync(int idPalabra) {
            return base.Channel.obtenerPalabraPorIDAsync(idPalabra);
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.Mensaje actualizarIDRetador(int idRetador, int idPartida) {
            return base.Channel.actualizarIDRetador(idRetador, idPartida);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.Mensaje> actualizarIDRetadorAsync(int idRetador, int idPartida) {
            return base.Channel.actualizarIDRetadorAsync(idRetador, idPartida);
        }
        
        public System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.PuntajeGlobal> obtenerPuntajeGlobal(int idUsuario) {
            return base.Channel.obtenerPuntajeGlobal(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProyectoAhorcado.ServiciosAhorcado.PuntajeGlobal>> obtenerPuntajeGlobalAsync(int idUsuario) {
            return base.Channel.obtenerPuntajeGlobalAsync(idUsuario);
        }
    }
}
