//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAhorcado.ServiciosAhorcado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaLogin", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class RespuestaLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoAhorcado.ServiciosAhorcado.Usuario InformacionUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsuarioCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoAhorcado.ServiciosAhorcado.Usuario InformacionUsuario {
            get {
                return this.InformacionUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionUsuarioField, value) != true)) {
                    this.InformacionUsuarioField = value;
                    this.RaisePropertyChanged("InformacionUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioCorrecto {
            get {
                return this.UsuarioCorrectoField;
            }
            set {
                if ((this.UsuarioCorrectoField.Equals(value) != true)) {
                    this.UsuarioCorrectoField = value;
                    this.RaisePropertyChanged("UsuarioCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosAhorcado.Modelo.Poco")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMaternoField, value) != true)) {
                    this.apellidoMaternoField = value;
                    this.RaisePropertyChanged("apellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPaternoField, value) != true)) {
                    this.apellidoPaternoField = value;
                    this.RaisePropertyChanged("apellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosAhorcado.IAhorcadoSVC")]
    public interface IAhorcadoSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/LogIn", ReplyAction="http://tempuri.org/IAhorcadoSVC/LogInResponse")]
        ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/LogIn", ReplyAction="http://tempuri.org/IAhorcadoSVC/LogInResponse")]
        System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin> LogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/checarLetra", ReplyAction="http://tempuri.org/IAhorcadoSVC/checarLetraResponse")]
        System.Collections.Generic.List<int> checarLetra(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/checarLetra", ReplyAction="http://tempuri.org/IAhorcadoSVC/checarLetraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> checarLetraAsync(char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/iniciarJuego", ReplyAction="http://tempuri.org/IAhorcadoSVC/iniciarJuegoResponse")]
        void iniciarJuego(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAhorcadoSVC/iniciarJuego", ReplyAction="http://tempuri.org/IAhorcadoSVC/iniciarJuegoResponse")]
        System.Threading.Tasks.Task iniciarJuegoAsync(string palabra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAhorcadoSVCChannel : ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AhorcadoSVCClient : System.ServiceModel.ClientBase<ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC>, ProyectoAhorcado.ServiciosAhorcado.IAhorcadoSVC {
        
        public AhorcadoSVCClient() {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AhorcadoSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AhorcadoSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<ProyectoAhorcado.ServiciosAhorcado.RespuestaLogin> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
        
        public System.Collections.Generic.List<int> checarLetra(char letra) {
            return base.Channel.checarLetra(letra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> checarLetraAsync(char letra) {
            return base.Channel.checarLetraAsync(letra);
        }
        
        public void iniciarJuego(string palabra) {
            base.Channel.iniciarJuego(palabra);
        }
        
        public System.Threading.Tasks.Task iniciarJuegoAsync(string palabra) {
            return base.Channel.iniciarJuegoAsync(palabra);
        }
    }
}
